name: zulutime_tracker
description: Cross-platform desktop time tracking and productivity monitoring with privacy-first design.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  window_manager: ^0.4.3
  supabase_flutter: ^2.10.0
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^6.1.1
  hid_monitor: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.staging
    - .env.production
    - assets/images/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: assets/images/logog.png
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: assets/images/logog.png
  windows:
    generate: true
    image_path: assets/images/logog.png
  web:
    generate: true
    image_path: assets/images/logog.png
    background_color: "#121212"
    theme_color: "#121212"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#121212"
  image: assets/images/splash.png
  android: true
  ios: true
  android_12:
    color: "#121212"
    image: assets/images/splash.png
